name: "Sonassi OpenVPN Connect"
description: "Connect to Sonassi OpenVPN"
branding:
  color: "blue"
  icon: "lock"
inputs:
  config_file:
    description: "The OpenVPN configuration file"
    required: true
  certificate:
    description: "The OpenVPN certificate"
    required: true
  certificate_name:
    description: "The OpenVPN certificate name as declared in the configuration file"
    required: true
    default: "certificate.p12"
  tmp_dir:
    description: "The temporary directory to store the OpenVPN configuration and certificate"
    required: true
    default: "/tmp"
runs:
  using: "node20"
  main: "dist_main/index.js"
  post: "dist_post/index.js"