name: Test

on:
    push:
        branches:
            - main
            - develop
    pull_request:

env:
  TMP_DIR: "/tmp"

jobs:
    test:
        runs-on: ubuntu-22.04
        name: Test usage of OpenVPN
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install OpenVPN
              run: |
                  sudo apt-get update
                  sudo apt-get install -y openvpn=2.5.9-0ubuntu0.22.04.3 openvpn-systemd-resolved
        
            - name: Test OpenVPN
              uses: "./"
              with:
                  config_file: ${{ secrets.VPN_CONFIG }}
                  certificate: ${{ secrets.VPN_CERTIFICATE }}
                  certificate_name: ${{ secrets.VPN_CERTIFICATE_NAME }}
                  tmp_dir: ${{ env.TMP_DIR }}

            - name: Wait for VPN to connect
              if: success()
              run: until ping -c 1 -W 5 172.16.0.61; do sleep 2; done

            - name: Upload VPN logs
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: vpn-logs
                  path: ${{ env.TMP_DIR }}/openvpn.log